# Generated by Django 3.1.3 on 2023-04-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0011_keyword_mastercontract_municipality_provision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="municipality",
            name="nonWhitePop2010",
        ),
        migrations.AddField(
            model_name="municipality",
            name="departmentObj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PxPUC.department",
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="department",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
