# Generated by Django 3.1.3 on 2023-04-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0013_auto_20230409_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="nonWhitePop2010",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="acreArea",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
