# Generated by Django 3.1.3 on 2023-04-09 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0014_auto_20230409_1227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="departmentObj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="munici",
                to="PxPUC.department",
            ),
        ),
    ]
