# Generated by Django 3.1.3 on 2023-04-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0015_auto_20230409_1257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="fullOfficers2019",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="partOfficers2019",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
