# Generated by Django 3.1.3 on 2023-04-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0016_auto_20230409_1319"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="mContractObj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dept",
                to="PxPUC.mastercontract",
            ),
        ),
    ]
