# Generated by Django 3.1.3 on 2023-04-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0018_auto_20230409_1523"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provision",
            name="keywords",
        ),
        migrations.AddField(
            model_name="keyword",
            name="provisions",
            field=models.ManyToManyField(related_name="keyw", to="PxPUC.Provision"),
        ),
    ]
